/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import LayoutWrapper from "@/components/CommonComponents/LayoutWrapper";
import Providers from "@/redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Management Dashboard",
  description: "Generated by Rahul Mallik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <StyledComponentsRegistry>
          <AntdRegistry>
            {/* Wrapping the entire application with Providers to ensure that Redux state is accessible throughout the app, including the LayoutWrapper and all its child components. */}
            <Providers>
              <LayoutWrapper>{children}</LayoutWrapper>
            </Providers>
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
